permalink: /:year/:month/:day/:title.html	#博客的固定链接
paginate: 10					#分页时每页博文数量
author:						#自定义常量
  name: Ian
  email: 2111519011@e.gzhu.edu.cn
  link: https://ian-jhon.github.io
title: 云烟阁					#自定义常量
locals:						#自定义常量
  tags: 标签
  about: 关于
active: 技术					#自定义常量
subscribe_rss: /pages/atom.xml			#订阅地址
markdown: redcarpet				#markdown解释器
#现在除了disqus和googleanalytics外都可以在这里配置了。